version: "2.1"

##############################
### default configurations ###
##############################

# docker logging
x-logging: &logging
  driver: json-file
  options:
    max-size: 5m

# containers restart policy
x-restart: &restart-policy on-failure

# aliases for hosts in docker networks
x-networks:
  api-netwok:
    - &cli
      aliases:
        - cli

##########################
### segmented networks ###
##########################
networks:
  # network for backend api access
  gateway_api_network:

###############################
### docker-compose services ###
###############################
services:
  # cli service
  cli:
    image: mamosk/ubuntu:${UBUNTU_VERSION:-20.10}
    container_name: ${KATA}_cli
    restart: *restart-policy
    build:
      context: ./bash
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION:-20.10}
    env_file: .env
    logging: *logging
    volumes:
      # script mounted as volume (edit made simple)
      - ./bash/katacli.sh:/kata/cli.sh:ro
    networks:
      gateway_api_network:
