version: "2.1"

##############################
### default configurations ###
##############################
x-logging: &logging
  driver: json-file
  options:
    max-size: 5m
x-restart: &restart-policy on-failure

###############################
### docker-compose services ###
###############################
services:
  # timelines api service
  nodered:
    image: mamosk/nodered-kata:1.0.0
    container_name: ${KATA}_nodered
    restart: *restart-policy
    build:
      context: ./build/nodered
    env_file: .env
    ports:
      - 11881:1881
    volumes:
      - ./nodered:/kata/flows
    depends_on:
      - influxdb
    logging: *logging

  # timelines db service
  influxdb:
    image: influxdb:1.8
    container_name: ${KATA}_influxdb
    restart: *restart-policy
    environment:
      - INFLUXDB_DB=kata
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    ports:
      - 18086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
    logging: *logging

  # timeline db configuration service
  chronograf:
    image: chronograf:1.8
    container_name: ${KATA}_chronograf
    restart: *restart-policy
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    ports:
      - 127.0.0.1:18888:8888
    volumes:
      - chronograf_data:/var/lib/chronograf
    depends_on:
      - influxdb
    logging: *logging

############################
### docker-managed stuff ###
############################
volumes:
  influxdb_data:
  chronograf_data:
