version: "2.1"

##################
### DISCLAIMER ###
##################
# Services ports are exposed to the host machine in order to quickly inspect what's going on.
# There's a '1' digit prepended to all standard ports: this hopefully will prevent port conflicts.
# In production environments ports should not be exposed (they're accessed within Docker networks).

##############################
### default configurations ###
##############################

# docker logging
x-logging: &logging
  driver: json-file
  options:
    max-size: 5m

# containers restart policy
x-restart: &restart-policy on-failure

# node-red is used for two services
x-nodered:
  image: &nodered-image mamosk/nodered-kata:${NODERED_VERSION:-1.1.1}
  build: &nodered-build
    context: ./nodered
    args:
      - NODERED_VERSION=${NODERED_VERSION:-1.1.1}

##########################
### segmented networks ###
##########################
networks:
  # network for users 'timelines' services
  timelines_api_network:
  timelines_db_network:
  # network for users 'followers' services
  followers_api_network:
  followers_db_network:

###############################
### docker-compose services ###
###############################
services:
  # api gateway service
  api_gateway:
    image: *nodered-image
    container_name: ${KATA}_nodered_gateway
    restart: *restart-policy
    build: *nodered-build
    env_file: .env
    depends_on:
      - timelines_api
      - followers_api
    logging: *logging
    volumes:
      - ./nodered/gateway:/kata/flows
    networks:
      - timelines_api_network
      - followers_api_network
    ports:
      - 11881:1881

  # timelines api service
  timelines_api:
    image: *nodered-image
    container_name: ${KATA}_nodered_timelines
    restart: *restart-policy
    build: *nodered-build
    env_file: .env
    environment:
      - INFLUXDB_HOST=timelines_db
    depends_on:
      - timelines_db
    logging: *logging
    volumes:
      - ./nodered/timelines:/kata/flows
    networks:
      - timelines_api_network
      - timelines_db_network
    ports:
      - 11888:1881

  # timelines db service
  timelines_db:
    image: influxdb:${INFLUXDB_VERSION:-1.8}
    container_name: ${KATA}_influxdb
    restart: *restart-policy
    environment:
      - INFLUXDB_DB=kata
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    logging: *logging
    volumes:
      - timelines_db_data:/var/lib/influxdb
    networks:
      - timelines_db_network
    ports:
      - 18086:8086

  # timeline db admin service
  timelines_db_admin:
    image: chronograf:${CHRONOGRAF_VERSION:-1.8}
    container_name: ${KATA}_chronograf
    restart: *restart-policy
    environment:
      - INFLUXDB_URL=http://timelines_db:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    depends_on:
      - timelines_db
    logging: *logging
    volumes:
      - timelines_db_admin_data:/var/lib/chronograf
    networks:
      - timelines_db_network
    ports:
      - 127.0.0.1:18888:8888

  # followers api service
  followers_api:
    image: mamosk/openjdk:${JAVA_VERSION:-8u201-jdk-alpine}
    container_name: ${KATA}_java
    restart: *restart-policy
    build:
      context: ./java
      args:
        - JAVA_VERSION=${JAVA_VERSION:-8u201-jdk-alpine}
        - JAVA_CONFIG=${JAVA_CONFIG}
    env_file: .env
    environment:
      - JAVA_OPTS=-Xms32m -Xmx128m
      - POSTGRES_URL=jdbc:postgresql://followers_db:5432/kata
    depends_on:
      - followers_db
    logging: *logging
    volumes:
      - ./java/src/main/resources/application.yml:${JAVA_CONFIG}/application.yml:ro
    networks:
      - followers_api_network
      - followers_db_network
    ports:
      - 18080:8080

  # followers db service
  followers_db:
    image: postgres:${POSTGRES_VERSION:-13}
    container_name: ${KATA}_postgres
    restart: *restart-policy
    environment:
      - POSTGRES_DB=kata
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging: *logging
    volumes:
      - followers_db_data:/var/lib/postgresql/data/
    networks:
      - followers_db_network
    ports:
      - 15432:5432

  # followers db admin service
  followers_db_admin:
    image: dpage/pgadmin4:${PGADMIN_VERSION:-4}
    container_name: ${KATA}_followers_db_admin
    restart: *restart-policy
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USERNAME}
    depends_on:
      - followers_db
    logging: *logging
    volumes:
      - followers_db_admin_data:/root/.pgadmin
      - ./postgres/servers.json:/pgadmin4/servers.json:ro
    networks:
      - followers_db_network
    ports:
      - 15050:80

########################################
### docker-managed persisted volumes ###
########################################
volumes:
  # volumes for users 'timelines' services
  timelines_db_data:
  timelines_db_admin_data:
  # volumes for users 'followers' services
  followers_db_data:
  followers_db_admin_data:
