spring:
  # PostgreSQL (data source)
  datasource:
    username: K
    password: villaggio
    url: jdbc:postgresql://localhost:15432/kata
  # Hibernate (data management)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
